# Generated by Django 4.2.5 on 2023-09-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_category', models.CharField(max_length=50, verbose_name='MEALS')),
                ('no_of_category', models.IntegerField()),
                ('items_in_a_category', models.CharField(max_length=50)),
                ('date_of_categorysale', models.DateTimeField()),
                ('address', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('category_type', models.CharField(choices=[('M D', 'MAIN DISH'), ('C D', 'COLD DRINKS'), ('T', 'TEA'), ('D', 'DISSERTS')], max_length=100)),
            ],
        ),
    ]
