# Generated by Django 4.2.5 on 2023-09-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mambo', '0003_category_description_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('table_type', models.CharField(choices=[('S', 'SINGLE'), ('D', 'DOUBLE'), ('G', 'GROUP')], max_length=25)),
                ('status', models.CharField(choices=[('O', 'OCCUPIED'), ('V', 'VACCANT')], max_length=20)),
            ],
        ),
    ]
