# Generated by Django 4.2.5 on 2023-09-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mambo', '0004_customer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('served_by', models.CharField(max_length=20)),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mambo.dish', verbose_name='Your dish')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mambo.customer_table', verbose_name='Your table')),
            ],
        ),
    ]
