# Generated by Django 4.2.5 on 2023-10-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mambo', '0007_rename_category_id_dish_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='customer_table',
            name='table_id',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='dish_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
